- lib/ClusterShell/NodeSet.py
Needed to easily change the patterns ClusterShell.NodeSet parses and
thus use it in pre-existing project where usual patterns are already
meaningful.
> Engine: declared bracket symbols as attributes of the ParsingEngine

- doc/man/man1/clubak.1
- doc/sphinx/tools/clubak.rst
- doc/txt/clubak.txt
Debian lintian tool is complaining :
spelling-error-in-manpage
usr/share/man/man1/clubak.1.gz additonal additional
> manpage: Fix typo additonal -> additional

- lib/ClusterShell/NodeSet.py
The difference_update() methods in NodeSet and NodeSetBase classes don't return any object, they update the current instance. Modified the documentation accordingly.
> Fix documentation for NodeSet difference_update()

- lib/ClusterShell/Worker/Ssh.py
man ssh-config says that "For each parameter, the first obtained value will
be used", but it turns out that it is not the case for short format ssh
options, like '-x' or '-a'. For them last specified value wins, making
impossible for user to override those. Using only long format options will
let users override hardwired values.
Closes #340
> Ssh: use long-format hardwired ssh options (#340) 

- lib/ClusterShell/Engine/EPoll.py
- lib/ClusterShell/Engine/Poll.py
Force the timeout to be exactly `-1` when is negative. The implementation
of the `poll()` system call in some OSes, including macOS and BSDs, throws
an error for arbitrary negative values different from `-1`.
Fix #353
> EnginePoll/EngineEpoll: fix polling timeout

- conf/groups.conf.d/slurm.conf.example
* shortcuts for group names
* better filtering of states and partition names with '*'
* added job bindings
> Update Slurm bindings

- doc/sphinx/release.rst
Same patch with a well formatted commit message
> doc/sphinx: add missing argument of ev_hup

- conf/groups.conf.d/slurm.conf.example
- doc/sphinx/config.rst
We have found the need to execute a parallel command on all nodes running jobs belonging to a particular user. If you add a "slurmuser" section to the /etc/clustershell/groups.conf.d/slurm.conf file, you can now run commands such as:
$ clush -bw@su:username 'df -Ph /scratch'
$ clush -bw@su:username 'du -s /scratch/username'
I hope that others may find this feature useful.
> Added configuration section for section slurmuser,su

- conf/groups.conf.d/xcat.conf.example
`lsdef` seems to be much quicker than `nodels` for large groups, especially for dynamic groups.
> xCAT bindings: performance update

- doc/sphinx/conf.py
Disable `smartquotes` mechanism (called `html_use_smartypants` in
older Sphinx versions) to prevent quotes and dashes to be converted to
lang-specific entities.
Closes #402.
> doc/sphinx: disable smartquotes

- conf/groups.conf.d/slurm.conf.example
Fix issue with the `slurmuser` binding, that was using job ids instead of user names.
> Slurm bindings

- doc/man/man1/clush.1
- doc/txt/clush.txt
Hi,
Here is a small PR for a doc fix.
'man clush' says that '%r'  is correct for the exec worker. It should be '%n'.
Cheers,
Romain Fihue
> doc: fix typo, %r is not for rank

- lib/ClusterShell/NodeSet.py
The `*_update` functions operate on a NodeSet in-place and return `None`.  Make this clearer so someone doesn't attempt to do `s = s.intersection_update(t)`
> Clarify NodeSet docs on functions that do not return a NodeSet

- doc/man/man1/clush.1
- doc/sphinx/tools/clush.rst
- lib/ClusterShell/Defaults.py
- tests/DefaultsTest.py
If a worker is specified with a '.' in the name, assume it is a
fully qualified module name that should be used.  This supports
custom worker classes that are distributed outside of ClusterShell.
> Allow out-of-tree worker modules

- conf/groups.d/cluster.yaml.example
- doc/sphinx/config.rst
- lib/ClusterShell/NodeUtils.py
- tests/NodeSetGroupTest.py
Allow the use of YAML list syntax when defining node groups.
> NodeUtils: allow YAML list to declare node groups

- lib/ClusterShell/CLI/Clush.py
Also allow manually-instantiated OutputHandlers to specify an alternate program
name.
Closes #433
Signed-off-by: Matt Ezell <ezellma@ornl.gov>
> CLI/Clush: Use the program name in OutputHandlers and RunTimer

- lib/ClusterShell/Gateway.py
- lib/ClusterShell/Task.py
- lib/ClusterShell/Worker/Tree.py
- tests/TreeWorkerTest.py
Do not hard-coding Exec as the Tree LocalWorker; instead use the
Task's info local_workername or the Default local_workername.
Closes #435.
> Tree: Allow alternate Local Workers in Tree Mode

- clustershell.spec.in
- openSUSE:Factory has dropped python2
- Add 'Obsoletes:' for leftover python2 package.
- '%license' instead of '%doc' is required for license files
- '%else if' isn't allowed for older rpm versions
- fix License string
- add '%fdupes' at end of %install section
Signed-off-by: Egbert Eich <eich@suse.com>
> Fix spec file to work with openSUSE

- clustershell.spec.in
This fixes Issue #445.
Thanks to Matt Ezell from  Oak Ridge.
Signed-off-by: Egbert Eich <eich@suse.com>
> Fix logic for detecting if Python2 is supported

- conf/groups.conf.d/xcat.conf.example
What do you mean group name shouldn't contain spaces?
> xCAT binding: add support for spaces in group names.

- lib/ClusterShell/Worker/Rsh.py
Fixes the following warning:
Rsh.py:77: DeprecationWarning: invalid escape sequence \d
match = re.search("^XXRETCODE: (\d+)$", msg.decode())
Signed-off-by: Stephane Thiell <sthiell@stanford.edu>
> Worker.Rsh: use raw string in RshClient

- conf/clush.conf
- doc/extras/vim/syntax/clushconf.vim
- doc/man/man1/clush.1
- doc/man/man5/clush.conf.5
- doc/sphinx/config.rst
- doc/txt/clush.conf.txt
- doc/txt/clush.txt
- lib/ClusterShell/CLI/Clush.py
- lib/ClusterShell/CLI/Config.py
- lib/ClusterShell/CLI/OptionParser.py
- tests/CLIClushTest.py
- tests/CLIConfigTest.py
Externalize the -S option as "maxrc" in the configuration file to
avoid passing it on the command line on every invocation.
> Add maxrc Option to clush.conf

- lib/ClusterShell/Task.py
- lib/ClusterShell/Worker/Tree.py
Intermediate gateways create a TreeWorker with a topology passed by
the parent node and a new root node, and instantiate their own
PropagationNodeRouter object.
When such TreeWorker is scheduled, we should set the task's default
router from it properly.
The error seen was:
...
File "ClusterShell/Propagation.py", line 411, in ev_close
self.task.router.mark_unreachable(gateway)
AttributeError: 'NoneType' object has no attribute 'mark_unreachable'
Fixes #471
> tree mode: fix error with intermediate gateways (#471)

- conf/groups.conf.d/slurm.conf.example
Slurm 21.08 introduced a new node state flag (^), and we missed a few before.
See https://slurm.schedmd.com/sinfo.html#SECTION_NODE-STATE-CODES for a complete list
> slurm.conf.example: Filter out more Slurm node state flags

- doc/man/man1/cluset.1
- doc/man/man1/nodeset.1
- doc/sphinx/tools/nodeset.rst
- doc/txt/cluset.txt
- doc/txt/nodeset.txt
- lib/ClusterShell/NodeSet.py
- tests/NodeSetGroupTest.py
This change allows access to all group names of a specific source in
node set expressions. The special operator `@@` followed by the source
expands group names that can then be manipulated as a set.
Note: In that case, group names are not prefixed with @ and as such, not
further expanded into nodes by NodeSet.
> NodeSet: add special notation @@source to expand group names

- lib/ClusterShell/CLI/Clush.py
- tests/CLIClushTest.py
Pass explicit stdin boolean flag when calling Task.shell() to fix an
issue where the stdin stream of the worker is never closed, even if
not used.
This change should not impact any already working stdin workflow.
However, the following command from a tty should not block anymore:
$ clush -w nodes cat
> clush: always close stdin stream of worker when it is not used

- lib/ClusterShell/CLI/Nodeset.py
- lib/ClusterShell/RangeSet.py
- tests/RangeSetTest.py
This change adds RangeSet.intiter() to explicily request an iterator
over the indexes of the set as integers. It is highly recommended to use
intiter() or striter() when iterating over RangeSet.
> RangeSet: add explicit intiter() method to iterate over integers

- lib/ClusterShell/CLI/Clush.py
- tests/TaskPortTest.py
setDaemon() has been deprecated since Python 3.10.
Use daemon property of threading.Thread() instead. It is available since
Python 2.6.
Fixes:
Clush.py:651: DeprecationWarning: setDaemon() is deprecated, set the
daemon attribute instead
> clush: use daemon attribute instead of deprecated setDaemon()

- lib/ClusterShell/Worker/Tree.py
- tests/TreeWorkerTest.py
With the help of an EnginePort object used for Engine control and write
message queueing, this change implements:
(1) a proper asynchrounous start for TreeWorker, which is now only
triggered when the engine actually starts
(2) buffered early writes
> Worker.Tree: fix start and bufferize early writes

- conf/clush.conf
- doc/extras/vim/syntax/clushconf.vim
- doc/man/man1/clush.1
- doc/man/man5/clush.conf.5
- doc/sphinx/config.rst
- doc/sphinx/tools/clush.rst
- doc/txt/clush.conf.txt
- doc/txt/clush.txt
- lib/ClusterShell/CLI/Clush.py
- lib/ClusterShell/CLI/Config.py
- lib/ClusterShell/CLI/Error.py
- lib/ClusterShell/Worker/Pdsh.py
- tests/CLIClushTest.py
Add support for sudo password prompt and forwarding over stdin to a
predefined sudo command. The sudo password is then sent over stdin
to the target nodes that will run the actual command prefixed by
the sudo command.
Add sudo_command option to clush.conf.
Closes #234.
> clush: add --sudo support (#234)

- doc/examples/defaults.conf-rsh
- doc/sphinx/config.rst
- doc/sphinx/release.rst
- doc/txt/clush.conf.txt
- doc/txt/clush.txt
- doc/txt/groups.conf.txt
- lib/ClusterShell/Defaults.py
- tests/CLIConfigTest.py
Introduce `$CLUSTERSHELL_CFGDIR` as an alternate location for configuration files.
This is basically a revisit of #191. This original issue led to #111, which allows *per-user* configuration file overrides, but doesn't provide a way to define system-wide configuration files (not per-user), which are not stored in `/etc`.
The use case is a multi-node cluster, where ClusterShell could be provided as a user-facing tool, installed on a shared file system (like a NFS mount point), and not as a local package on each node. In that case, providing system defaults for all users would requiring distributing configuration files on each and every of the cluster node's local `/etc/` directory. A more flexible approach would be to define an environment variable (the proposed `$CLUSTERSHELL_CFGDIR`) to …
> Introduce $CLUSTERSHELL_CFGDIR 

- lib/ClusterShell/Task.py
- tests/TaskPortTest.py
...by using current_thread() and notify_all() instead of the deprecated
currentThread() and notifyAll() functions. This fixes
DeprecationWarnings from the test suite that end up as errors.
AFAICT, the new names have been available since python-2.6[1], so this
change should not break support for any current python versions.
[1] https://docs.python.org/2.6/library/threading.html#threading.current_thread
https://docs.python.org/2.6/library/threading.html#threading.Condition.notify_all
> Fix for python-3.10

- tests/CLIConfigTest.py
The `CLI.Config.ClushConfig (setrlimit)` test fails with `python3.10` with an error:
```
resource.setrlimit(resource.RLIMIT_NOFILE, (hard2/2, hard))
TypeError: 'float' object cannot be interpreted as an integer
```
The integer division solves the problem.
> CLIConfigTest: Use integer division for soft limit computation

- clustershell.spec.in
py2 has been removed from SLES as of 15sp4
https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP4/index.html#jsc-SLE-16747
> Disable python2 on SLES15sp4 and newer

- lib/ClusterShell/Defaults.py
Fix an issue building the config paths list when `CLUSTERSHELL_CFGDIR` is not defined (extra `%s` in path).
> Fix error in building config paths list

- lib/ClusterShell/Worker/Worker.py
- tests/TaskDistantMixin.py
Remove deprecated methods:
- Worker.last_error()
- Worker.last_node()
- Worker.last_read()
- Worker.last_retcode()
They have been deprecated since at least v1.6.
> Worker: remove old last_*() methods (#226)

- lib/ClusterShell/Worker/Worker.py
- tests/TaskDistantMixin.py
- tests/TaskDistantPdshMixin.py
- tests/TaskEventTest.py
- tests/TaskLocalMixin.py
- tests/TaskMsgTreeTest.py
- tests/TaskThreadJoinTest.py
- tests/TaskTimerTest.py
- tests/WorkerExecTest.py
Old EventHandler signatures (eg. ev_read(self, worker)) have been deprecated since 1.8. This patch adds DeprecationWarnings for 1.9.
Also deprecating Worker.current_* variables in the documentation.
New EventHandler's method arguments should be used instead.
Also updated all tests that were still relying on old signatures.
Closes #358.
> Worker: deprecate old EventHandler method signatures (#358)

- lib/ClusterShell/Event.py
- tests/TaskEventTest.py
Commit 269ddbd7b0e65be062ea81ad13c0d45d546b6d36 for #358 introduced a DeprecationWarning for ev_timeout() which doesn't work without removing the method definition from EventHandler.
Remove the definition from the class, add specific test and update documentation.
> Event: remove ev_timeout() definition

- lib/ClusterShell/Worker/EngineClient.py
Use more robust formatting in case the streams are not initialized yet.
Fixes #499.
> EnginePort: use %s format instead of %d in __repr__()

- tests/CLIClushTest.py
- tests/TaskDistantMixin.py
- tests/TaskDistantPdshMixin.py
- tests/TreeWorkerTest.py
- tests/WorkerExecTest.py
Inspired by arkamar/gentoo@1d69b11373706f2ce4c60670eace674ae0c766c0
> tests: skip tests that require HOSTNAME != 'localhost'

- tests/StreamWorkerTest.py
An unconfigured StreamWorker does not have streams to register in the engine, so when registered, it stays until it is explicitly aborted. To make that worse, it is using a 'fanout slot' and if the Engine's fanout is too low, it can lead to the engine run loop exiting prematurely. This is not a case handled very well by the Engine. See #497 for more details about the problem.
In the meantime, we fix the test to exit with a clean engine state.
Fixes #488.
> tests: fix StreamWorker test leading to bad Engine state

- lib/ClusterShell/CLI/Config.py
Fix a defect to actually select the last parsed config file, otherwise $CFGDIR in confdir is broken when /etc/clustershell exists.
Fixes #511.
> clush: select proper last parsed config file (#511)

- clustershell.spec.in
- doc/sphinx/config.rst
- doc/sphinx/install.rst
- lib/ClusterShell/Defaults.py
- setup.py
- tests/CLIConfigTest.py
- remove root exception handling
- include man pages as data_files
- check for config files in sys.prefix/etc/clustershell
- if $CLUSTERSHELL_CFGDIR is defined, always try it first
This allows clustershell to be installed as user in a venv using pip
install or using pip install --user with man pages.
Root installation using pip is now discouraged. If done, /usr/local is
likely to be used as the install prefix.
Fixes #389.
> setup.py: improvements for pip install and venv

- doc/man/man1/clush.1
- doc/txt/clush.txt
- lib/ClusterShell/CLI/OptionParser.py
correct typo from 'sterr' to 'stderr'
> correct typo 'sterr'

- lib/ClusterShell/NodeSet.py
From pylint:
NodeSet.py:63:0: C0413: Import "from ClusterShell.Defaults import config_paths, DEFAULTS" should be placed at the top of the module (wrong-import-position)
NodeSet.py:68:0: W0611: Unused RangeSetException imported from ClusterShell.RangeSet (unused-import)
NodeSet.py:69:0: W0611: Unused RangeSetPaddingError imported from ClusterShell.RangeSet (unused-import)
> NodeSet: a few minor code fixes

- mkrpm.sh
SLES15sp4 doesn't have `python` installed, so fall back to `python3`
> Use python3 if python is not installed

- .readthedocs.yaml
- doc/sphinx/conf.py
- lib/ClusterShell/Engine/Engine.py
- lib/ClusterShell/MsgTree.py
- lib/ClusterShell/NodeSet.py
- lib/ClusterShell/NodeUtils.py
- lib/ClusterShell/Task.py
- lib/ClusterShell/Worker/Exec.py
- lib/ClusterShell/Worker/Popen.py
- lib/ClusterShell/Worker/Worker.py
See: https://blog.readthedocs.com/use-build-os-config/
Also `enable fail_on_warning`.
> readthedoc: migrate to build.os + docstring fixes (#529)

- doc/sphinx/tools/clush.rst
- doc/sphinx/tools/nodeset.rst
- lib/ClusterShell/Topology.py
- tests/TreeTopologyTest.py
Router and destination node sets defined in topology.conf may use NodeSet groups and wildcards but those have to resolve to non-empty node sets when we build the tree.
Add checks for this in the code and add a note to the documentation.
Fixes #527.
> Topology: check that node groups/wildcards are non-empty (#527)

- doc/sphinx/config.rst
- lib/ClusterShell/NodeUtils.py
- tests/NodeSetGroupTest.py
An empty group can already be defined by specifying an empty string as value in the yaml file.
For convenience, now also interpret any YAML null value as an empty set.
Fixes #533.
> NodeUtils: allow null values in cluster.yaml (#533)

- lib/ClusterShell/CLI/Clubak.py
- lib/ClusterShell/CLI/Display.py
- tests/CLIClubakTest.py
- tests/CLIDisplayTest.py
- tests/TLib.py
When the code was ported to Python 3, we switched to sys.stdout.buffer and sys.stderr.buffer that use BufferedWriter (bytes) for printing outputs. However, this method doesn't work great for line buffering, which is used a lot by clush and clubak.
Switch back to sys.stdout and sys.stderr, as TextIOWrapper objects, which take strings and benefit from automatic line buffering. If stdout (or stderr) is not a tty, we reconfigure it (only once) to force line buffering. Indeed, clush and clubak might be piped to other tools (like pv) that expects each line to be flushed.
Key points of this patch:
- write() to stdout/stderr now takes a string and the Display class is in charge of performing the needed bytes-to-string decoding
- any non-printable character will be decoded to U+FFFD thanks to …
> CLI: fix line buffering with Python 3 (#528)

- doc/man/man1/clush.1
- doc/sphinx/tools/clush.rst
- doc/txt/clush.txt
- lib/ClusterShell/CLI/Clush.py
- tests/CLIClushTest.py
When multiple files or directories are specified as arguments with --[r]copy, and --dest is omitted, use each argument's dirnname for each destination, instead of the dirname of the first argument only.
Fixes #525.
> clush: fix --[r]copy dest when --dest is omitted (#525)

- ChangeLog
Seems like I forget to check the ChangeLog file at the root of the repository last time.
By the way congratulation for the 1.9.2 release.
> Fix few typos in ChangeLog found by codespell

- doc/sphinx/tools/clush.rst
LLNL pdsh URL broken; Updating link to LLNL software catalog pdsh page.
> Update clush.rst to fix broken URL for llnl.gov pdsh page

- lib/ClusterShell/CLI/Clush.py
- lib/ClusterShell/Worker/Tree.py
- tests/CLIClushTest.py
Using a NodeSet to track a large and frequent-changing set of remote
targets can lead to performance issue as reported in #560, especially
when RangeSetND is involved.
Use a standard set instead for gwtargets tracking in the TreeWorker
and adapt clush to work with sets in that case.
Fixes #560
> Tree: use set instead of NodeSet for gwtargets tracking

- conf/groups.conf.d/slurm.conf.example
Provide more Slurm example bindings, to interact with nodes running jobs from specific accounts, or under specific QOSes.
Generate a folded nodeset from all the nodes running jobs from the `myacc` Slurm account:
```
$ cluset -f @slurmaccount:myacc
```
Count the number nodes running jobs submitted with the `long` QOS:
```
$ cluset -f @slurmqos:long
```
> Additional Slurm example bindings

- conf/groups.conf.d/slurm.conf.example
To list nodes in reservation `foobar`
```
$ cluset -f @sr:foobar
sh02-01n60
```
To list reservations that node `sh03-01n72` is part of:
```
$ cluset -ll -s slurmresv sh03-01n72
@slurmresv:test sh03-01n72
$ cluset -f @slurmresv:test
sh03-01n[71-72]
```
> Additional Slurm binding for mapping nodes to reservations

- .github/workflows/nosetests.yml
This is to address the warning about deprecated Node.js
> GitHub Actions: update actions to their latest versions

- tests/TreeGatewayTest.py
Hi! :wave: 
It was reported that the clustershell test suite breaks with Expat >=2.6.0 (https://bugs.gentoo.org/924601). So this pull request fixes the test suite for Expat >=2.6.0 with CPython 3.13 and backport releases by using the new pyexpat API (https://github.com/python/cpython/issues/115398). There is no rush in merging this, we can definitey wait for that APi to become more widely available if you like, it will likely appear in these very CPython releases:
- 3.8.19
- 3.9.19
- 3.10.14
- 3.11.9
- 3.12.3
- 3.13.0
I should note that Python 3.7 and earlier are dead, hence related pull request #555.
I'm looking forward to your review, maybe I missed something :beers: 
Best, Sebastian
> Fix tests for libexpat >=2.6.0 (or with CVE-2023-52425 fixes backported)

- lib/ClusterShell/Communication.py
This is due to libexpat 2.6 reparse deferral as documented in #556.
Unfortunately ExpatParser doesn't seem to have SetReparseDeferralEnabled(), so we use an explicit flush() call to make sure all handlers are called immediately. We control the source XML.
NOTE: Only available in Python 3.13 and backports.
> Communication: sax parser: add flush() after feed() (#556)

- lib/ClusterShell/CLI/Nodeset.py
- tests/CLINodesetTest.py
Let -s source behave as if it replaces the default group source, and thus omit the source prefix for the groups in that source.
Part of #563.
> CLI/Nodeset: omit @source: prefix for cluset -s source -L (#563)

- MANIFEST.in
- bash_completion.d/cluset
- bash_completion.d/clush
- clustershell.spec.in
- lib/ClusterShell/CLI/Nodeset.py
- lib/ClusterShell/CLI/OptionParser.py
- tests/CLINodesetTest.py
Just clush for now; might be some bugs but seems to work.
perf-wise it calls `cluset -L` on every tab, we might need to cache the result somewhere if it is slow in some setups.
(But if user changes conf files it won't be reloaded so that's a bit annoying, it's better not to cache if it's reasonable e.g. just reading the conf files)
Prereq patch makes `cluset -s foo -L` not list `foo` groups with the `@foo:` prefix, like default source with `-L` -- this allows `clush -s foo -w @bar` to complete properly.
> bash completions

- lib/ClusterShell/NodeUtils.py
Some commands consume stdin when they shouldn't, but we shouldn't have been giving stdin to upcalls in the first place.
Reported-by: Kilian Cavalotti <kilian@stanford.edu>
replaces #580
> NodeUtils: do not pass stdin to group upcalls
